name: Check Pull request validity
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  check-commit-messages:
    name: Check commit messages
    runs-on: ubuntu-latest
    steps:
      - name: Get commits
        id: get-commits
        uses: tim-actions/get-pr-commits@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check commit name length
        if: ${{ success() || failure() }}
        uses: tim-actions/commit-message-checker-with-regex@v0.3.1
        with:
          commits: ${{ steps.get-commits.outputs.commits }}
          pattern: '^.{0,90}(\n.*)*$'
          error: 'Commit name too long (max 90)'

      - name: Check prefix
        if: ${{ success() || failure() }}
        uses: tim-actions/commit-message-checker-with-regex@v0.3.1
        with:
          commits: ${{ steps.get-pr-commits.outputs.commits }}
          pattern: '^[\h]*([^:\h\n]+)[\h]*:'
          error: 'Missing prefix in commit name'
